### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Borda** [Rockhopper-Technologies/enlighten#9] opened 2019-10-29 12:56 UTC
Not sure if it is related to the `enlighten` itself or the error is somewhere else, but I am receiving the following error:
```
Traceback (most recent call last):
  File "bm_experiments/bm_DROP2.py", line 228, in <module>
    arg_params, path_expt = BmDROP2.main()
  File "~/Repos/BIRL/birl/benchmark.py", line 632, in main
    benchmark.run()
  File "~/Repos/BIRL/birl/utilities/experiments.py", line 139, in run
    self._run()
  File "~/Repos/BIRL/birl/benchmark.py", line 299, in _run
    aggr_experiments=True)
  File "~/Repos/BIRL/birl/benchmark.py", line 318, in __execute_method
    for res in iterate_mproc_map(method, iter_table, nb_workers=nb_workers, desc=desc):
  File "~/Repos/BIRL/birl/utilities/experiments.py", line 547, in iterate_mproc_map
    stream=sys.stderr)
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/enlighten/counter.py", line 31, in __init__
    counter_class=self.__class__, set_scroll=False)
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/enlighten/_manager.py", line 401, in get_manager
    return Manager(stream=stream, counterclass=counterclass, **kwargs)
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/enlighten/_manager.py", line 78, in __init__
    self.term = Terminal(stream=self.stream)
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/enlighten/_terminal.py", line 26, in __init__
    super(Terminal, self).__init__(*args, **kwargs)
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/blessed/terminal.py", line 238, in __init__
    self.__init__keycodes()
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/blessed/terminal.py", line 300, in __init__keycodes
    locale.setlocale(locale.LC_ALL, '')
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
Running on the following machine:
* `posix.uname_result(sysname='Linux', nodename='cmpgrid-68', release='4.9.0-6-amd64', version='#1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)', machine='x86_64')`
* Python 3.6.6 (default, Mar 11 2019, 11:55:52) [GCC 7.3.0] on linux
* pip 19.2.1 from `/home.dokt/borovji3/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/pip` (python 3.6)
* `enlighten==1.4.0`

**Comment by avylove** [comment] 2019-10-29 13:23
I've seen this issue on Python 2 on Windows (Blessed includes a workaround), but not on Python 3 or on Linux. Essentially the issue is ``locale.setlocale`` doesn't seem to support your user language settings. Blessed sets the locale for keyboard input. Enlighten doesn't use this feature, but it's automatic and never caused issues in the past.

Are you running blessed 1.16.1?
What is the output of ``locale`` when run from the command line? 
Is this running under the Linux Subsystem for Windows?

**Comment by Borda** [comment] 2019-10-29 13:38
> Are you running blessed 1.16.1?

I don't see `blessed` among installed packages

> What is the output of `locale` when run from the command line?

yes, terminal

> Is this running under the Linux Subsystem for Windows?

no, pure Linux #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)

**Comment by avylove** [comment] 2019-10-29 13:43
Please run these two commands on the terminal. I've included output so you know what to expect.

```console
$ python -c 'import blessed; print(blessed.__version__)'
1.16.1

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by avylove** [comment] 2019-10-29 14:11
For the first one, use whatever command you use to launch python, it may be ``python3`` or ``python36``.

For the second one, the error that comes up may be related. Basically, I think there is an issue with the locales configuration on your system. You don't happen to be SSHing from a Mac, are you?

I'm not a Debian user and the commands are different on Fedora, so I can't test this out for you, but this guide seems to be pointing in the right direction, though you'd replace de_DE.UTF-8 with cs_CZ.UTF-8.
https://www.forwardproxy.com/2018/12/how-to-fix-locale-problems-on-debian-and-ubuntu/

**Comment by avylove** [comment] 2019-10-29 14:39
Blessed is installed in your virtual environment (/home.dokt/borovji3/TEMP/Applications/vEnv3.6) so you'd have to activate that first. That said, I'm pretty sure it's 1.16.1 since that version is required for Enlighten 1.4.0

Let me know how it goes. If you resolve the issues with the ``locale`` command and are still having issues running Enlighten, we can dig further, but my guess is that should fix it.

**Comment by Borda** [comment] 2019-10-29 14:58
you are right wit the virtual environment...
```
you are right wit the virtual environment...
```
:~$ python -c 'import blessed; print(blessed.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/blessed/__init__.py", line 13, in <module>
    from blessed.terminal import Terminal
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/blessed/terminal.py", line 49, in <module>
    from .sequences import (SequenceTextWrapper,
  File "~/TEMP/Applications/vEnv3.6/lib/python3.6/site-packages/blessed/sequences.py", line 13, in <module>
    import wcwidth
ModuleNotFoundError: No module named 'wcwidth'
```

**Comment by avylove** [comment] 2019-11-04 17:05
It still looks a little strange. When you installed Enlighten 1.4.0, Blessed 1.16.1 and wcwidth should have been installed.

**Comment by avylove** [comment] 2019-11-10 13:43
Did you sort this out? Ok for me to close?

**Comment by Borda** [comment] 2019-11-10 13:51
I did not have time for it so I swapped temporary back to TQDM...

**Comment by avylove** [comment] 2019-11-11 14:22
Since this isn't an Enlighten issue, I'm going to go ahead and close this. Should just be a matter of getting your system encodings set up and everything should work fine. Once ``locale`` returns without errors, let me know if you have any other issues.

**Closed by avylove** 2019-11-11 14:22 UTC

**Comment by avylove** [comment] 2020-05-25 03:07
We made some changes in Blessed that should let things work normally with your configuration. Please upgrade Blessed to 1.17.6 or higher and see if you're still getting errors.
