### ISSUE TITLE
Newline before progressbar

### ISSUE THREAD

**Issue by AdrienPensart** [Rockhopper-Technologies/enlighten#31] opened 2020-09-04 00:03 UTC
**Describe the bug**
Some newlines are present before progress bars

**To Reproduce**
examples/context_manager.py

**Environment (please complete the following information):**
 - Enlighten Version: 1.6.2
 - OS and version: WSL2 (Windows 10 + Ubuntu 18.04)
 - Console application: wsl-terminal + nested tmux (2x tmux)
 - Special Conditions: no

**Additional context**
enlighten/_manager.py : line 314
```python
# Save scroll offset for resizing
oldOffset = self.scroll_offset
newOffset = max(self.counters.values()) + 1
```
When I delete the +1, it works well.
newOffset = max(self.counters.values())

When printing 100 lines of "Hello world", the terminal is scrolling and I still have my 100 lines of precedent output, no lines were eaten by the progress bars, so is this +1 really necessary ?

**Comment by avylove** [comment] 2020-09-04 02:52
The +1 is to add a single empty line between the scroll region and the progress bars.

Are you saying you have more than one new line above the top progress bar or that you would prefer to have no empty lines above the progress bars?

**Comment by avylove** [comment] 2020-11-27 19:33
I can't reproduce. Removing the +1 would make the scroll region end on the same line as the progress bard begin. This actually seems to be ok with the logging library and in case where you do a line feed before writing to the terminal like `sys.stdout.write('\n' + 'Hello')`, but not for the standard print statement.

I'm going to close this, but feel free to respond with sample code if you're getting different results.

**Closed by avylove** 2020-11-27 19:33 UTC
Labels: Info Needed
