### ISSUE TITLE
[LOW PRIORITY] Fix progress bar in terminal in IntelliJ

### ISSUE THREAD

**Issue by robert-kapala-mox** [Rockhopper-Technologies/enlighten#51] opened 2022-11-23 15:40 UTC
First of, let me say thank you for good job!
`enlighten` is working fine and we all love it.

It so nice piece of software that we would like to run it in our favourite IDE.
In the IntelliJ terminal the progress bar does not look good as it should (additional enters).

I will understand if you close as "Won't do" because of very niche usage.
Nevertheless, it is worth trying :)

**Comment by avylove** [comment] 2022-12-01 02:45
Closing as a duplicate of #32

**Closed by avylove** 2022-12-01 02:45 UTC
Labels: bug

**Comment by PouriaDiesel** [comment] 2024-06-06 08:59
my problem was Pycharm not showing progressbars in termial but I checked `Emulate terminal in output console` in `Run->Edit Configurations` and now it's showing. more details in [this link](https://stackoverflow.com/a/48002833/7848924)
