### ISSUE TITLE
OSError: [WinError 6] The handle is invalid.

### ISSUE THREAD

**Issue by evandrocoan** [Rockhopper-Technologies/enlighten#4] opened 2019-05-05 20:53 UTC
This error happens for all examples on the first page, as this one:
````python
import time
import enlighten

manager = enlighten.get_manager()
ticks = manager.counter(total=100, desc='Ticks', unit='ticks')
tocks = manager.counter(total=20, desc='Tocks', unit='tocks')

for num in range(100):
    time.sleep(0.1)  # Simulate work
    print(num)
    ticks.update()
    if not num % 5:
        tocks.update()

manager.stop()
````

`python3 version 3.7.2, Windows 10`

``` 
Traceback (most recent call last):
  File "D:\User\Downloads\text2.py", line 4, in <module>
    manager = enlighten.get_manager()
  File "F:\Python\lib\site-packages\enlighten\_manager.py", line 397, in get_manager
    return Manager(stream=stream, counterclass=counterclass, **kwargs)
  File "F:\Python\lib\site-packages\enlighten\_manager.py", line 78, in __init__
    self.term = Terminal(stream=self.stream)
  File "F:\Python\lib\site-packages\enlighten\_terminal.py", line 32, in __init__
    super(Terminal, self).__init__(*args, **kwargs)
  File "F:\Python\lib\site-packages\enlighten\_win_terminal.py", line 144, in __init__
    enable_vt_mode(self.stream_fh)
  File "F:\Python\lib\site-packages\enlighten\_win_terminal.py", line 109, in enable_vt_mode
    KERNEL32.GetConsoleMode(filehandle, ctypes.byref(current_mode))
  File "F:\Python\lib\site-packages\enlighten\_win_terminal.py", line 71, in _check_bool
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 6] The handle is invalid.
```

**Comment by avylove** [comment] 2019-05-05 20:59
Are you running within an IDE like PyCharm or Visual Studio?

**Comment by evandrocoan** [comment] 2019-05-05 21:02
I ran in Sublime Text and on Cygwin (mintty.exe). 

But now I just tested all examples on `cmd.exe` and they all worked right.

**Comment by avylove** [comment] 2019-05-05 21:11
Since terminal scrolling is very dependent on the terminal, sometimes it doesn't play well inside some IDE terminals. I haven't tried Sublime yet. It's possible it could, it just hasn't come up yet.

Cygwin should work, but under Cygwin it shouldn't need to use the Windows terminal module, it should just use the standard one. So that may be a bug, what does `platform.system()` return under cygwin?

**Comment by evandrocoan** [comment] 2019-05-05 21:22
If I use `Anaconda Python 3 for windows` it shows Windows
If I use `Cygwin Python 2` it shows CYGWIN
```
Professional@PROFESSIONAL-PC$ python3 text2.py
platform Windows
Professional@PROFESSIONAL-PC$ python text2.py
('platform', 'CYGWIN_NT-10.0')
```

I am inside Cygwin, but I am using Cygwin's Python.

If I install Cygwin Python, it works fine. Only using Anaconda Python on Cygwin mintty terminal breaks things.

**Comment by avylove** [comment] 2019-05-05 21:33
My guess is Cygwin Python is overwriting the platform module behavior, but Anaconda Python doesn't know it's inside a  Cygwin terminal. I think I need to set it up and see what it looks like. Might need an additional test to check for this condition.

I'll have to look at Sublime too. IDEs that use the native terminal are easy, when they use their own terminal it really depends on how well-implemented it is and how easy it is to detect when you're inside it.

**Comment by evandrocoan** [comment] 2019-05-05 21:35
Sublime Text does not have full terminal features:
1. https://github.com/SublimeTextIssues/Core/issues/1468 Full/complete terminal features on Sublime Text

**Comment by evandrocoan** [comment] 2019-05-05 21:47
I used this script to install Cygwin: https://github.com/evandrocoan/CygwinPortable/blob/master/cygwin-portable-installer.cmd

You just need to download the file, open it, and wait until it finishes.

It will install Python 2 and 3 with pip2 and pip3.

To instal new packages you can use `apt-cyg install` or `apt-cyg find something`

**Comment by avylove** [comment] 2019-05-05 22:54
Terminus in Sublime seems to work fine for me. You get the same error?

I'm having problems launching an external Python from within Cygwin, it just hangs. Can you check a couple things for me?
 - If you `import blessed` with the trouble Python environment, does it raise any warnings?
- What does os.environ['OSTYPE'] show?
- What does os.environ['MACHTYPE'] show?

**Comment by evandrocoan** [comment] 2019-05-05 23:06
> I'm having problems launching an external Python from within Cygwin, it just hangs. Can you check a couple things for me?

On Cygwin you need to launch the Windows Python with the `-i` argument, i..e, `python -i` or just call `python script.py`.

![image](https://user-images.githubusercontent.com/5332158/57201580-343e5a80-6f71-11e9-8275-218186c71aa0.png)

**Comment by avylove** [comment] 2019-05-05 23:57
I see two problems.
The first is there doesn't seem to be a reliable way to detect you're running under Cygwin in this scenario. The best I've seen is TERM=xterm in the environ variables and that stdin is a io.TextIOWrapper type. 

The second is Python for Windows doesn't include the curses library, which blessed uses to determine the terminal codes.

The Cywin terminal does seem xterm compliant, so it might be possible to create an xterm terminal library similar to the Windows one and fall back to it when running xterm under windows without real file handles for stdout. That should work. I just have to make sure I can get the terminal size accurately.

Did Enlighten with Terminus work for you in Sublime?

**Comment by evandrocoan** [comment] 2019-05-06 00:09
Yes. Terminus defaulted to use `cmd.exe` in the background, and it works fine with `cmd.exe`. I tried to use `bash.exe` from `Cygwin` with Terminus, but it did the same error:

![image](https://user-images.githubusercontent.com/5332158/57202284-f2fe7880-6f79-11e9-9e11-7b8edd803192.png)

**Comment by avylove** [comment] 2019-05-06 01:01
The problem is you're half in Windows, half in Cygwin. Basically you have a *Nix terminal environment and only Windows tools to manipulate it. Both usually want the real file descriptor, which is unavailable.

I think I could do something to make it function, but I still need the terminal size. I can tell the terminal to give me it's size, but I can't find a way to read it because I can't change the mode of the terminal so it won't buffer it.

**Comment by evandrocoan** [comment] 2019-05-06 01:03
You could ignore the terminal size and set the minimum size when you cannot get it.

**Comment by avylove** [comment] 2019-05-06 01:13
Not really. Too many things depend on the terminal size. I could force a resize, but that could be very problematic if the terminal is embedded within a frame of another application.

**Comment by avylove** [comment] 2019-05-10 22:34
I'm going to close this one. I can't see a way to support your configuration. I'd like to, but it would be a fragile implementation for a limited use case. If you can find a way to get the terminal size reliably, I think we could put something together. That said, the only way I found to do it was to go looking for the Cygwin stty command, shelling out, and calling it. That's not reliable since I can't even confirm when it's using the Cygwin terminal.

What I'd really like is generic support for xterm terminals, and xterm lets you ask for the terminal size with `sys.stdout.write(u'\x1B[18t')`, but that gets reported back through the terminal itself, not one of the standard streams, so as far as I can tell, it's not internally accessible. Typically you'd use use a platform-specific interface to get this (tputs, ioctl, GetConsoleScreenBufferInfo), but, in your configuration, the available interfaces are Windows when the Linux interfaces are needed.

**Closed by avylove** 2019-05-10 22:34 UTC

**Comment by avylove** [comment] 2019-11-10 14:00
You should see this fail gracefully in the latest version. Basically, if it can't access a real file handle, it should just not print progress bars, but the program will continue.
